paramset:
- datset: GFSPRS
  grid_num: 0
  sub_center: ncep_nco
  version_no: v2003
  local_table_vers_no: local_tab_yes1
  sigreftime: fcst
  prod_status: oper
  data_type: fcst
  gen_proc_type: fcst
  time_range_unit: hour
  orig_center: nws_ncep
  gen_proc: gfs_avn
  packing_method: complex_packing_spatial_diff
  order_of_sptdiff: 2nd_ord_sptdiff
  field_datatype: fltng_pnt
  comprs_type: lossless
  param:
  - post_avblfldidx: 464
    shortname: EDPARM_ON_ISOBARIC_SFC
    longname: '?'
    mass_windpoint: 1
    pdstmpl: tmpl4_0
    pname: EDPARM
    table_info: '?'
    stats_proc: '?'
    fixed_sfc1_type: isobaric_sfc
    scale_fact_fixed_sfc1: ['?']
    level: [14750, 19680, 25000, 30090, 34430, 39270]
    fixed_sfc2_type: '?'
    scale_fact_fixed_sfc2: ['?']
    level2: ['?']
    aerosol_type: '?'
    prob_type: '?'
    typ_intvl_size: '?'
    scale_fact_1st_size: 0
    scale_val_1st_size: 0
    scale_fact_2nd_size: 0
    scale_val_2nd_size: 0
    typ_intvl_wvlen: '?'
    scale_fact_1st_wvlen: 0
    scale_val_1st_wvlen: 0
    scale_fact_2nd_wvlen: 0
    scale_val_2nd_wvlen: 0
    scale_fact_lower_limit: 0
    scale_val_lower_limit: 0
    scale_fact_upper_limit: 0
    scale_val_upper_limit: 0
    scale: [3]
    stat_miss_val: 0
    leng_time_range_prev: 0
    time_inc_betwn_succ_fld: 0
    type_of_time_inc: '?'
    stat_unit_time_key_succ: '?'
    bit_map_flag: '?'
  - post_avblfldidx: 480
    shortname: ICESEV_ON_ISOBARIC_SFC
    longname: '?'
    mass_windpoint: 1
    pdstmpl: tmpl4_0
    pname: ICESEV
    table_info: '?'
    stats_proc: '?'
    fixed_sfc1_type: isobaric_sfc
    scale_fact_fixed_sfc1: ['?']
    level: [39270, 50600, 59520, 69680, 84310]
    fixed_sfc2_type: '?'
    scale_fact_fixed_sfc2: ['?']
    level2: ['?']
    aerosol_type: '?'
    prob_type: '?'
    typ_intvl_size: '?'
    scale_fact_1st_size: 0
    scale_val_1st_size: 0
    scale_fact_2nd_size: 0
    scale_val_2nd_size: 0
    typ_intvl_wvlen: '?'
    scale_fact_1st_wvlen: 0
    scale_val_1st_wvlen: 0
    scale_fact_2nd_wvlen: 0
    scale_val_2nd_wvlen: 0
    scale_fact_lower_limit: 0
    scale_val_lower_limit: 0
    scale_fact_upper_limit: 0
    scale_val_upper_limit: 0
    scale: [1]
    stat_miss_val: 0
    leng_time_range_prev: 0
    time_inc_betwn_succ_fld: 0
    type_of_time_inc: '?'
    stat_unit_time_key_succ: '?'
    bit_map_flag: '?'
