name: GCC Linux Build
on: [push, pull_request, workflow_dispatch]


# Use custom shell with -l so .bash_profile is sourced
# without having to do it in manually every step
defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  CC: gcc-10
  FC: gfortran-10
  CXX: g++-10
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# The jobs are split into:
# 1. a dependency build step (setup), and
# 2. a UPP build step (build)
# The setup is run once and the environment is cached,
# so each build of UPP can reuse the cached dependencies to save time (and compute).

jobs:
  setup:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout-upp  # This is for getting spack.yaml
        uses: actions/checkout@v4
        with:
            path: UPP

      # Cache spack, compiler and dependencies
      - name: cache-env
        id: cache-env
        uses: actions/cache@v4
        with:
          path: |
            spack
            ~/.spack
          key: spack-${{ runner.os }}-gcc-${{ hashFiles('UPP/ci/spack.yaml', 'UPP/modulefiles/**', 'UPP/.github/workflows/gcc.yml') }}

      # Install dependencies using Spack
      - name: install-dependencies-with-spack
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          git clone -c feature.manyFiles=true https://github.com/NOAA-EMC/spack.git
          cd spack
          ./REMOVE_SPACK_STACK_MODS_FOR_CI.sh
          source share/spack/setup-env.sh
          spack env create upp-env ../UPP/ci/spack.yaml
          spack env activate upp-env
          sudo apt install cmake doxygen
          spack external find
          spack add mpich@3.4.2
          spack concretize
          spack install -v --fail-fast --dirty
          spack clean --all

  build:
    needs: setup
    runs-on: ubuntu-22.04

    steps:
      - name: checkout-upp
        uses: actions/checkout@v4
        with:
            path: UPP

      - name: cache-env
        id: cache-env
        uses: actions/cache@v4
        with:
          path: |
            spack
            ~/.spack
          key: spack-${{ runner.os }}-gcc-${{ hashFiles('UPP/ci/spack.yaml', 'UPP/modulefiles/**', 'UPP/.github/workflows/gcc.yml') }}

      - name: build-upp
        run: |
          sudo apt install doxygen
          source spack/share/spack/setup-env.sh
          spack env activate upp-env
          export CC=mpicc
          export FC=mpif90
          cd UPP
          mkdir -p build && cd build
          cmake -DENABLE_DOCS=ON -DCMAKE_INSTALL_PREFIX=../install ..
          make -j2 VERBOSE=1
          ctest --output-on-failure
          make install
