name: Intel Linux Build
on: [push, pull_request, workflow_dispatch]

# Use custom shell with -l so .bash_profile is sourced which loads intel/oneapi/setvars.sh
# without having to do it in manually every step
defaults:
  run:
    shell: bash -leo pipefail {0}

# Set I_MPI_CC/F90 so Intel MPI wrapper uses icc/ifort instead of gcc/gfortran
env:
  CC: icc
  FC: ifort
  CXX: icpc
  I_MPI_CC: icc
  I_MPI_F90: ifort
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# The jobs are split into:
# 1. a dependency build step (setup), and
# 2. a UPP build step (build)
# The setup is run once and the environment is cached,
# so each build of UPP can reuse the cached dependencies to save time (and compute).

jobs:
  setup:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout-upp  # This is for getting spack.yaml
        if: steps.cache-env.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
            path: UPP

      # Cache spack, compiler and dependencies
      - name: cache-env
        id: cache-env
        uses: actions/cache@v4
        with:
          path: |
            spack
            ~/.spack
            /opt/intel
          key: spack-${{ runner.os }}-intel-${{ hashFiles('UPP/ci/spack.yaml', 'UPP/modulefiles/**', 'UPP/.github/workflows/intel.yml') }}

      - name: install-intel-compilers
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo gpg --dearmor -o /usr/share/keyrings/oneapi-archive-keyring.gpg GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install intel-oneapi-dev-utilities intel-oneapi-mpi-devel intel-oneapi-openmp intel-oneapi-compiler-fortran-2023.2.1 intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2023.2.1
          echo "source /opt/intel/oneapi/setvars.sh --force" >> ~/.bash_profile

      # Install dependencies using Spack
      - name: install-dependencies-with-spack
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          git clone -c feature.manyFiles=true https://github.com/NOAA-EMC/spack.git
          cd spack
          ./REMOVE_SPACK_STACK_MODS_FOR_CI.sh
          source share/spack/setup-env.sh
          spack env create upp-env ../UPP/ci/spack.yaml
          spack env activate upp-env
          source /opt/intel/oneapi/setvars.sh --force
          spack compiler find
          sudo apt install cmake doxygen
          spack external find
          spack add intel-oneapi-mpi
          spack concretize
          spack install --dirty -v --fail-fast
          spack clean --all

  build:
    needs: setup
    runs-on: ubuntu-22.04

    steps:
      - name: checkout-upp
        uses: actions/checkout@v4
        with:
            path: UPP

      - name: install-intel
        run: |
          echo "source /opt/intel/oneapi/setvars.sh --force" >> ~/.bash_profile

      - name: cache-env
        id: cache-env
        uses: actions/cache@v4
        with:
          path: |
            spack
            ~/.spack
            /opt/intel
          key: spack-${{ runner.os }}-intel-${{ hashFiles('UPP/ci/spack.yaml', 'UPP/modulefiles/**', 'UPP/.github/workflows/intel.yml') }}

      # Build UPP
      - name: build-upp
        run: |
          sudo apt install doxygen
          source spack/share/spack/setup-env.sh
          spack env activate upp-env
          export CC=mpiicc
          export FC=mpiifort
          cd UPP
          mkdir -p build && cd build
          cmake -DENABLE_DOCS=ON -DCMAKE_INSTALL_PREFIX=../install ..
          make -j2 VERBOSE=1
          ctest --output-on-failure
          make install
